supervisor nice option
laravel/horizon pull request #551
Opened 2019-03-19 10:10 UTC by halaei

Closing #549 
I don't know if you can regard it as backward compatible because of the change in supervisor option constructor. Also not sure if it has to be sent to 3.0 or master.

2019-03-19 10:15 UTC, driesvints commented
It's backwards compatible because adding constructor arguments with defaults won't break anything. This is fine 👍

2019-03-19 10:19 UTC, driesvints commented
@halaei Also: always add the full description for this PR to your main comment and not just link to a issue/pull request.

2019-03-19 10:22 UTC, halaei commented
@driesvints Updated comment

2019-03-19 10:26 UTC, halaei commented
Reading code, I see a --paused option:

    {--paused : Start the supervisor in a paused state}

Reading that, I wish there was an option to pause a supervisor for a few seconds before starting to scale for the first time. maybe a `--pause=10` option.

2019-03-19 14:02 UTC, taylorotwell commented
The PHP documentation states that the `proc_nice` value can also be negative?

2019-03-19 14:11 UTC, halaei commented
@taylorotwell It will only work if the process is running as a superuser, otherwise an exception will be raised with this message:

    proc_nice(): Only a super user may attempt to increase the priority of a process

2019-03-19 14:16 UTC, browner12 commented
Support for Windows does not exist until PHP 7.2. Do we need to do anything in code to account for that, or will that be a documentation solution?

2019-03-19 14:19 UTC, halaei commented
@browner12 This is an optional feature. If it is not supported on an environment you can simply not use it.

2019-03-19 14:26 UTC, driesvints commented
@browner12 Windows support is lacking in general: https://github.com/laravel/horizon/issues/170

2019-03-19 15:55 UTC, mfn requested changes
No happy about the `0` default and not allowing negative values!

2019-03-19 15:55 UTC, mfn commented on src/SupervisorOptions.php
> +    public $nice = 0;
This is problematic:
- a niceness of `0` is a valid value
- the (linux) default for niceness is usually `10`

IMHO the correct way is to use `null` here.

2019-03-19 15:55 UTC, mfn commented on src/Console/SupervisorCommand.php
> +                            {--nice=0 : The process niceness}
`0` is not a good value, see my other comment

2019-03-19 15:55 UTC, mfn commented on src/Console/SupervisorCommand.php
> +        if ($supervisor->options->nice > 0) {
- `0` is a valid niceness level
- so are negative values

This check, see my other comment, should be `!== null`

It doesn't matter that e.g. negative values are only allowed for root user rights. Don't outsmart the dev who might have run as root _for whatever_ reason, etc.

2019-03-19 16:06 UTC, halaei commented
@mfn The argument of proc_nice is the amount of **increment** to the niceness:

>  proc_nice ( int $increment ) : bool
proc_nice() changes the priority of the current process by the amount specified in increment.

http://php.net/manual/en/function.proc-nice.php

2019-03-19 16:09 UTC, halaei commented
@mfn zero increment means no increment, so no need for null. About letting user to use negative values, that is fine for me, although I don't feel I should use it or run my workers as sudo or use Windows at all ;)

2019-03-19 16:10 UTC, halaei commented
Maybe I should change the comments in the code from 'The process niceness' to 'Increment to the process niceness'?

2019-03-19 18:42 UTC, mfn commented
@halaei thanks for correcting me, you're right!

Still, I vote for allowing negative values. It's not your decision how others want to run the code.

2019-03-20 18:35 UTC, merged

2019-03-26 19:46 UTC, driesvints commented
This has now been released in v3.1.0

2024-08-19 10:11 UTC, Einenlum commented
This doesn't seem documented: https://laravel.com/docs/11.x/horizon
Could it be added to the documentation somewhere?